import type { ComponentType } from 'react'

/** Article bodies are discovered by glob: content/<section>/<sub>/<article>.mdx (lazy, code-split per article). */
const loaders = import.meta.glob<{ default: ComponentType }>('./content/*/*/*.mdx')
const toPath = (k: string) => k.replace('./content/', '').replace(/\.mdx$/, '')
const byPath = new Map(Object.entries(loaders).map(([k, l]) => [toPath(k), l]))

export const hasArticle = (path: string) => byPath.has(path)
export const loadArticle = (path: string) => byPath.get(path)?.()

/** group id ("T9A") -> compendium article paths that link to it. Generated by scripts/gen-compendium.ts; {} if absent. */
const links = import.meta.glob<Record<string, string[]>>('./generated/exam-links.json', { eager: true, import: 'default' })
export const examLinks: Record<string, string[]> = Object.values(links)[0] ?? {}

export interface SearchDoc { p: string; t: string; s: string; x: string }
const indexLoader = import.meta.glob<{ default: SearchDoc[] }>('./generated/search-index.json')
/** Lazy: only fetched the first time someone focuses the search box. */
export async function loadSearchIndex(): Promise<SearchDoc[]> {
  const l = Object.values(indexLoader)[0]
  return l ? (await l()).default : []
}
